NUbots/NUsight2

.travis.yml
src/client/components/localisation/tests/presenter.tests.ts

So now the green tick means slighty more by actually running the build and tslint 🙂

Add build, tslint and coverage to build pipeline

---

package.json

Fix yarn start on windows

---

.gitignore
.idea/NUsight2.iml
.idea/modules.xml

Based on https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

Fix included IntelliJ project files

---

src/client/components/localisation/style.css
src/client/components/localisation/view.tsx

This fixes the localisation window such that is shrinks to size when the window is made smaller 😄

Fix localisation canvas autosizing

---

webpack.config.ts

Superseded by https://github.com/NUbots/NUsight2/blob/1067a6c5e54977f60832c09d815c891797a50be4/src/server/dev.ts#L18

Remove unused webpack dev server settings

---

tsconfig.json

Reduced version of https://github.com/NUbots/NUsight2/pull/24

Clean up tsconfig

---

src/client/components/localisation/darwin_robot/model.ts
src/client/components/localisation/model.ts
src/client/components/localisation/utils.ts
src/client/components/localisation/view.tsx
src/client/index.tsx
tsconfig.json

Enable strictNullChecks

---

package.json
src/client/components/app/view.tsx
yarn.lock

* Use the chrome extension instead:
https://chrome.google.com/webstore/detail/mobx-developer-tools/pfgnfdagidkfgccljigdamigbcnndkod?hl=en

Remove mobx react devtools

---

src/client/components/localisation/view.tsx
src/client/index.tsx
src/inversify.config.ts

Removed the `Provider` component provided by `mobx-react` in favour of using the dependency injection provided by `inversify`.

Inject LocalisationModel into LocalisationView

---

src/client/components/navigation/style.css
src/client/components/navigation/view.tsx

Also updates the whole file to use spaces instead of tabs

Remove logo from Navigation

---

package.json
src/client/components/localisation/skybox/view_model.ts
src/simulators/nuclearnet/tests/fake_nuclearnet.tests.ts
src/simulators/sensor_data_simulator.ts
tslint.json
yarn.lock

Rather than relying on IntelliJ for formatting, this is an attempt to get `yarn run tslint:fix` to fix more styling things!

Add tslint-eslint-rules

---

.idea/NUsight2.iml

It seems I missed one rename in #28

Update IDEA configuration to ignore build directory

---

package.json
src/server/nuclearnet/fake_nuclearnet_server.ts
src/server/nuclearnet/tests/fake_nuclearnet_client.tests.ts
yarn.lock

Tests were failing, refactored them to be less fussy.

Update NUClearNet to 1.1.0

---

README.md
package.json

Add yarn dev as an alias to yarn start:sim

---

src/client/components/localisation/controller.ts
src/client/components/localisation/darwin_robot/body/view_model.ts
src/client/components/localisation/darwin_robot/view_model.ts
src/client/components/localisation/field/view_model.ts
src/client/components/localisation/model.ts
src/client/components/localisation/network.ts
src/client/components/localisation/skybox/skybox.vert
src/client/components/localisation/skybox/view_model.ts
src/client/components/localisation/tests/controller.tests.ts
src/client/components/localisation/view_model.ts
src/simulators/sensor_data_simulator.ts

Ensures:
* +X forward
* +Y left
* +Z up
* +R left

Use NUbots coordinate system for localisation tab

---

src/client/canvas/appearance/basic_appearance.ts
src/client/canvas/appearance/line_appearance.ts
src/client/canvas/geometry/arrow_geometry.ts
src/client/canvas/geometry/circle_geometry.ts
src/client/components/dropdown_container/view.tsx
src/client/components/switch/view.tsx
src/client/math/tests/vector2.tests.ts
src/client/math/transform.ts
src/client/math/vector2.ts
src/server/nbs/nbs_frame_codecs.ts
src/server/time/fake_clock.ts
tslint.json

Somehow I didn't add this already...

Enforce trailing commas style

---

src/shared/field/dimensions.ts

Based on new data here: https://github.com/NUbots/NUbots/pull/92, which includes physical measurements of the field.

Update field dimensions for RoboCup 2017

---

src/client/canvas/renderer.ts

This should fix the transforms and rendering in firefox.

Fix text geometry render transforms

---

src/client/math/matrix2.ts
src/client/math/matrix3.ts
src/client/math/vector2.ts
src/client/math/vector3.ts

These are needed to parse some of the messages that will be coming in the overview packet

Add Matrix2 and Matrix3 models

---

src/client/components/dashboard/ground/model.ts

Ensures the positive x axis faces the yellow goals.

Swap goals colours on dashboard

---

src/client/canvas/geometry/arc_geometry.ts
src/client/canvas/object/shape.ts
src/client/canvas/renderer.ts
src/client/components/dashboard/dashboard_robot/model.ts
src/client/components/dashboard/dashboard_robot/view_model.ts
src/client/components/dashboard/robot_panel/view.tsx
src/client/components/dashboard/robot_panel/view_model.ts
src/client/components/dashboard/view.tsx
src/simulators/overview_simulator.ts

Add walk command to dashboard

---

src/client/components/dashboard/controller.ts
src/client/components/dashboard/field/model.ts
src/client/components/dashboard/field/view_model.ts
src/client/components/dashboard/style.css
src/client/components/dashboard/view.tsx
src/client/index.tsx

Add field flip button to dashboard

---

src/client/canvas/renderer.ts
src/client/components/dashboard/field/controller.ts
src/client/math/transform.ts

Moving a camera to the left should move the objects it is looking at to the right.
Taking this out of https://github.com/NUbots/NUsight2/pull/127 so I can use it for other things!

Make the camera act like a camera

---

src/client/network/nusight_network.ts
src/virtual_robots/virtual_robot.ts

I have no idea if the C++ side is setup to work with this, though.
- #135
- #136
- #137 ← You are here

Remove NUsight networking header

---

src/client/components/localisation/field/view_model.ts
yarn.lock

Add the goal and penalty mark field lines

---

src/client/components/localisation/view.tsx

Fixes localisation controls broken from dependency upgrade.

Fix localisation controls

---

package.json

This makes it easy to open the repo on Github by running `npm repo`.
Also removed empty description, and moved licence up.

Add repository to package.json, to support `npm repo`

---

src/client/components/dashboard/dashboard_robot/model.ts
src/client/components/dashboard/dashboard_robot/view_model.ts
src/client/components/dashboard/ground/view_model.ts
src/client/render2d/appearance/basic_appearance.ts
src/client/render2d/appearance/line_appearance.ts
src/client/render2d/canvas/arc.ts
src/client/render2d/canvas/arrow.ts
src/client/render2d/canvas/circle.ts
src/client/render2d/canvas/marker.ts
src/client/render2d/canvas/polygon.ts
src/client/render2d/canvas/rendering.ts
src/client/render2d/canvas/tests/__snapshots__/rendering.tests.ts.snap
src/client/render2d/canvas/tests/rendering.tests.ts
src/client/render2d/pixi/rendering.ts
src/client/render2d/pixi/text.ts
src/client/render2d/svg/rendering.tsx
src/client/render2d/svg/tests/__snapshots__/arc.tests.tsx.snap
src/client/render2d/svg/tests/__snapshots__/arrow.tests.tsx.snap
src/client/render2d/svg/tests/__snapshots__/circle.tests.tsx.snap
src/client/render2d/svg/tests/__snapshots__/group.tests.tsx.snap
src/client/render2d/svg/tests/__snapshots__/line.tests.tsx.snap
src/client/render2d/svg/tests/__snapshots__/marker.tests.tsx.snap
src/client/render2d/svg/tests/__snapshots__/path.tests.tsx.snap
src/client/render2d/svg/tests/__snapshots__/polygon.tests.tsx.snap
src/client/render2d/svg/tests/__snapshots__/text.tests.tsx.snap

As more rendering engines have been implemented the appearance class has gotten harder to implement.
This refactors it so it is easier to use.

Refactor the Appearance class

---

jest.config.js
package.json
src/client/network/nusight_network.ts
src/client/nuclearnet/web_socket_proxy_nuclearnet_client.ts
src/server/dev.ts
src/server/nbs/mmap_nbs_player/nbs_player.cpp
src/server/nuclearnet/fake_nuclearnet_server.ts
src/server/nuclearnet/web_socket_server.ts
src/server/prod.ts
src/shared/network/nuclear_proxy_parser.ts
src/shared/nuclearnet/nuclearnet_proxy_parser.ts
src/shared/nuclearnet/nuclearnet_proxy_parser_socketio.ts
src/shared/nuclearnet/tests/nuclearnet_proxy_parser.tests.ts
yarn.lock

Results in much faster speeds as the buffers that come in off the network don't need to be sliced or manipulated.

Add a socket.io parser designed for the NUClearNet Proxy

---

.gitignore

Ignore log files

---

src/client/components/visual_mesh/camera/model.ts
src/client/components/visual_mesh/camera/shaders/mesh.frag
src/client/components/visual_mesh/camera/shaders/mesh.vert
src/client/components/visual_mesh/camera/view_model.ts
src/client/components/visual_mesh/network.ts
src/shared/proto/Matrix.proto
src/shared/proto/message/vision/VisualMesh.proto

Change how the data is transferred in order to improve performance and update drawing.
Classifications still need to be drawn properly in a future PR

Improve performance of VisualMesh

---

src/client/components/vision/camera/model.ts
src/client/components/vision/camera/shaders/world_line.frag
src/client/components/vision/camera/view_model.ts
src/client/components/vision/network.ts
src/shared/proto/message/input/Image.proto
src/shared/proto/message/output/CompressedImage.proto

Adds more lens projection types to the vision window

Add more lens projections to the vision window

---

src/client/components/app/model.ts
src/client/components/checkbox_tree/tree_node/view.tsx
src/client/components/dashboard/dashboard_robot/model.ts
src/client/components/dashboard/ground/model.ts
src/client/components/dropdown_container/view.tsx
src/client/components/localisation/darwin_robot/model.ts
src/client/components/localisation/model.ts
src/client/components/localisation/skybox/model.ts
src/client/components/localisation/view.tsx
src/client/components/robot/model.ts
src/client/render2d/canvas_renderer.tsx
src/client/render2d/pixi_renderer.tsx
src/server/nbs/tests/nbs_nuclear_playback.tests.ts
src/server/nuclearnet/fake_nuclearnet_client.ts
src/server/nuclearnet/fake_nuclearnet_server.ts
tsconfig.json

https://blog.mariusschulz.com/2018/05/20/typescript-2-7-strict-property-initialization

Enable strict property initialization

---

conf/storybook/build_storybook.js
conf/storybook/dev.js
conf/storybook/prod.js
conf/storybook/webpack.config.ts
declarations/connect-history-api-fallback.d.ts
package.json
src/server/prod.ts
yarn.lock

Add storybook to the main heroku build and deploy, accessed via `/storybook/`.
e.g. https://nusight-pr-212.herokuapp.com/storybook/

Add storybook to heroku

---

src/client/components/three/tests/three.tests.ts
src/client/components/three/three.tsx

Fixes those pesky memory leaks.

Reuse scene and camera objects

---

src/client/base/disposable_computed.ts
src/client/base/tests/disposable_computed.tests.ts
src/client/components/three/stories/three.stories.tsx

More memory leaks to disappear!

Add @disposableComputed

---

package.json
yarn.lock

Revert react-svg-loader upgrade

---

src/client/components/vision/camera/model.ts
src/client/components/vision/camera/view_model.ts
src/client/components/vision/network.ts
src/shared/proto/message/Geometry.proto
src/shared/proto/message/vision/Ball.proto
src/shared/proto/message/vision/GreenHorizon.proto
src/shared/proto/message/vision/VisualMesh.proto

Update ball rendering to suit new ball detector in NUbots

---

src/client/components/vision/camera/model.ts
src/client/components/vision/camera/view_model.ts
src/client/components/vision/network.ts
src/shared/proto/message/vision/Goal.proto
src/shared/proto/message/vision/VisualMesh.proto
src/virtual_robots/simulators/vision_simulator.ts

Update goal rendering to suit new NUbots goal detector

---

src/server/dev.ts
src/server/prod.ts
src/virtual_robots/run.ts
src/virtual_robots/virtual_robot.ts
src/virtual_robots/virtual_robots.ts

#276 missed support for `yarn virtual-robots --address x.x.x.x`, this PR adds it!

Add --address to yarn virtual-robots

---

src/client/components/vision2/camera/balls.ts
src/client/components/vision2/camera/compass.ts
src/client/components/vision2/camera/goals.ts
src/client/components/vision2/camera/horizon.ts
src/client/components/vision2/camera/model.ts
src/client/components/vision2/camera/stories/camera.stories.tsx
src/client/components/vision2/camera/view.tsx
src/client/components/vision2/camera/view_model.ts

https://nusight-vision-objects-qxhutkp.herokuapp.com/storybook/?path=/story/components-vision2-camera--vision-objects

Add CameraView with vision objects

---

src/client/components/vision2/camera/model.ts
src/client/components/vision2/camera/styles.css
src/client/components/vision2/camera/view.tsx
src/client/components/vision2/camera/view_model.ts

https://nusight-annable-vision-rxbdoac.herokuapp.com/storybook/?path=/story/components-vision2-camera--vision-objects

Vision 2: Add drawing options menu

---

conf/storybook/webpack.config.ts
yarn.lock

Storybook would not compile for me until I did this

Delete and recreate yarn.lock

---

conf/storybook/addons.ts
conf/storybook/webpack.config.ts
package.json
src/client/components/vision2/grid_layout/grid_layout.tsx
src/client/components/vision2/grid_layout/stories/grid_layout.stories.tsx
src/client/components/vision2/grid_layout/stories/styles.css
src/client/components/vision2/grid_layout/styles.css
yarn.lock

A grid layout component designed for use with vision, specifically picking the optimal number of columns to maximum the image to whitespace ratio.
Storybook: https://nusight-annable-grid-la-36lmgh.herokuapp.com/storybook/?path=/story/components-vision2-grid-layout--renders-static

Add GridLayout component

---

src/client/components/three/builders.ts
src/client/components/vision/camera/model.ts
src/client/components/vision/camera/shaders/visual_mesh.frag
src/client/components/vision/camera/shaders/visual_mesh.vert
src/client/components/vision/camera/view.tsx
src/client/components/vision/camera/view_model.ts
src/client/components/vision/camera/visual_mesh.ts
src/client/components/vision/model.ts
src/client/components/vision/network.ts
src/client/components/vision/view.tsx

No storybook yet, but works with an nbs file:

Add visual mesh support back to vision

---

src/client/base/compose.ts
src/client/base/tests/compose.tests.ts
src/client/components/three/three.tsx
src/client/nuclearnet/tests/web_socket_proxy_nuclearnet_client.tests.ts
src/client/nuclearnet/web_socket_proxy_nuclearnet_client.ts
src/client/nuclearnet/webworker_web_socket_client.worker.ts
src/server/dev.ts
src/server/nuclearnet/tests/web_socket_proxy_nuclearnet_server.tests.ts
src/server/nuclearnet/web_socket_proxy_nuclearnet_server.ts
src/server/nuclearnet/web_socket_server.ts
src/server/prod.ts

I reported this issue 3 years ago: https://github.com/NUbots/NUsight2/issues/121
I fixed it.

Fix websocket disconnects

---

src/client/components/vision/camera/shaders/line_projection.frag

As [reported by Aaron](https://nubotsteam.slack.com/archives/C3T1J8SGL/p1603755858002000) in Slack

Fix `unproject()` in line projection shader
