README.md
Adds a fancy live updating travis build status badge to the README 😄
=> Add travis build badge to README

src/server/dev.ts, webpack.config.ts
I thought they were broken, but they just weren't turned on.
This gives you your original source code in the chrome console during debugging, rather than your transpiled ES5 code.
Old:
New:
=> Fix sourcemaps

nodemon.json, package.json
Currently nodemon will restart the entire server when you make client-side changes, i.e. edit a file in `src/client`.
This is unneeded and makes development slow! So this PR makes nodemon ignore both tests and anything in `src/client`.
=> Make nodemon ignore client-side changes

declarations/connect-history-api-fallback.d.ts, declarations/express-history-api-fallback.d.ts, package.json, src/server/dev.ts, src/server/prod.ts, yarn.lock
- Replace express-history-api-fallback with connect-history-api-fallback.
- Update usages in dev and prod servers.
- Add custom typings for connect-history-api-fallback.
=> Fix fallback history api

.gitignore, package.json, src/server/dev.ts, src/server/prod.ts, tsconfig.json, webpack.config.ts
We don't have a distribution (we're not a library)... so build makes more sense.
Also removes any existing `build` dir on a build
=> Rename dist to build

webpack.config.ts
Ensures client-side libraries are added to `vendor.bundle.js` instead of `bundle.js`.
=> Add all libraries to vendor bundle

package.json, yarn.lock
* Fixes the console deprecation warning regarding PropTypes
=> Upgrade mobx-react-devtools

.travis.yml
Travis was complaining, so I followed https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
=> Use trusty for travis build

src/client/components/localisation/style.css, src/client/components/localisation/view.tsx, src/client/components/menu_bar/style.css, src/client/components/menu_bar/view.tsx
Extract simple menu bar component from localisation view so that other screens, such as configuration, can make use of it.
=> Add reusable menu bar

.travis.yml
By letting travis cache yarn dependencies we can speed up the build in travis a little.
=> Cache yarn to speed up the build in travis

webpack.config.ts
Lets us use the debugger on https://nusight.herokuapp.com/
=> Enable source maps on production

jest.config.js
CI is currently showing an error:
[`Failed to collect coverage from src/shared/proto/messages.d.ts`](https://travis-ci.org/NUbots/NUsight2/jobs/244400149#L377)
We don't need CI to run on the proto folder, so this PR updates the configuration to ignore it.
=> Update jest to ignore proto directory

.travis.yml, src/server/dev.ts
Travis was passing because it was caching `node_modules`, even when a dependency was deleted.
This removes the `node_modules` cache. It wasn't speeding up builds significantly enough to warrant potential false-positive builds.
First commit fails, as expected, then the second commit fixes the actual build error.
=> Remove node modules cache

package.json, yarn.lock
https://blogs.msdn.microsoft.com/typescript/2017/06/27/announcing-typescript-2-4/
=> Update TypeScript to version 2.4

src/client/components/app/network.ts, src/client/components/localisation/controller.ts, src/client/components/localisation/darwin_robot/body/view_model.ts, src/client/components/localisation/darwin_robot/head/view_model.ts, src/client/components/localisation/darwin_robot/left_arm/view_model.ts, src/client/components/localisation/darwin_robot/left_leg/view_model.ts, src/client/components/localisation/darwin_robot/model.ts, src/client/components/localisation/darwin_robot/right_arm/view_model.ts, src/client/components/localisation/darwin_robot/right_leg/view_model.ts, src/client/components/localisation/darwin_robot/view_model.ts, src/client/components/localisation/model.ts, src/client/components/localisation/network.ts, src/client/components/localisation/tests/controller.tests.ts, src/client/components/localisation/view_model.ts, src/client/components/robot/model.ts, src/client/index.tsx, src/client/network/nusight_network.ts, src/client/nuclearnet/web_socket_client.ts, src/client/nuclearnet/web_socket_proxy_nuclearnet_client.ts, src/server/nuclearnet/direct_nuclearnet_client.ts, src/server/nuclearnet/fake_nuclearnet_client.ts, src/tests/networking_integration.tests.ts
This PR adds full networking support for robots. That is to say, newly connected robots will automatically show up in the robot selector as well as in the localisation display.
Looks/works better with #75 + throttling though.
=> Add networked robots

src/client/components/app/network.ts
Without this fix, robots who reconnect would stop responding to messages since their port changed and wasn't updated.
=> Update port on reconnect

src/simulators/virtual_robots.ts
Just updating their NUClearNet names to match.
=> Rename Simulated Robot to Virtual Robot

src/client/nuclearnet/tests/web_socket_proxy_nuclearnet_client.tests.ts, src/client/nuclearnet/web_socket_proxy_nuclearnet_client.ts, src/server/dev.ts, src/server/nuclearnet/web_socket_proxy_nuclearnet_server.ts, src/server/prod.ts, src/simulators/simulate.ts
- Throttles unreliable packets so that we do not overwhelm the client with traffic.
- Sits between `WebSocketProxyNUClearNetServer` and `WebSocketProxyNUClearNetClient`.
- The limit is per-event, such that no particular event should be starved more than any other.
- The limit is per-robot, such that no robot is starved more than any other.
=> Add network throttling

src/server/nuclearnet/web_socket_proxy_nuclearnet_server.ts
Technically this shouldn't know robots exist, so renaming it.
=> Rename RobotMessageProcessor to PacketProcessor

declarations/xxhashjs.d.ts, package.json, src/server/nuclearnet/fake_nuclearnet_server.ts, yarn.lock
Uses [`xxhashjs`](https://github.com/pierrec/js-xxhash) to produce identical hash codes to NUClearNet.
Should be able to technically record virtual robots with this.
=> Upgrade NUClearNet.js to 1.2.0

src/client/components/robot_selector/style.css
See https://github.com/NUbots/NUsight2/issues/79
=> Align all robot switch icons to the right

src/client/base/memoize.ts, src/client/components/localisation/darwin_robot/model.ts, src/client/components/localisation/model.ts
Any current use `createTransformer` to transform from `A -> B` where `B` is not 100% derived from `A` will be lost when `B` goes out of scope.
e.g. Take for example, the transformation from `AppModel -> LocalisationModel`. In this case `LocalisationModel` is not 100% derived from `AppModel`, the first call adds a bunch of new properties and we mutate them over time. It is designed to be a long-lived object which should not disappear when switching to another tab, otherwise we will lose all our localisation state. We haven't noticed this behaviour for a few coincidental reasons, but since working on the other tabs this has come up.
This PR introduces a new function, `memoize`, which simply memoizes the mapping between `A` and `B` such that as long as `A` still exists, we will keep its …
=> Preserve non-derived models across tabs

src/server/nuclearnet/web_socket_proxy_nuclearnet_server.ts, src/server/time/clock.ts, src/server/time/node_clock.ts, src/simulators/sensor_data_simulator.ts, src/simulators/virtual_robot.ts
In the interest of keeping all our units consistently using the SI standard and reducing the number of conversions throughout the code, this PR updates all timers to operate in seconds.
=> Update all timers to use seconds

src/server/dev.ts
Essentially prevents the virtual robots from trying to send data before webpack fully loads.
Prevents the flood of packets once it does eventually load.
=> Wait for webpack before starting services

src/server/time/fake_clock.ts, src/server/time/tests/fake_clock.tests.ts
Add a fake synchronous clock to be used in tests, already using them in the upcoming nbs playback code. This lets you write unit tests for modules that deal with time, without the tests using real time. It implements the `Clock` interface.
API roughly based around jest timers https://facebook.github.io/jest/docs/timer-mocks.html
Featuring:
- `tick(delta: number = 1)` — Move forward time a relative amount.
- `runAllTimers()` — Recursively run all scheduled timers, including any that those timers schedule themselves.
- `runOnlyPendingTimers()` — Run all scheduled timers, excluding any additional scheduled timers.
- `runTimersToTime(time: number)` — Move forward time to an absolute point.
If you're wondering why not use jest timers? They are somewhat incompatible with dependency injection. …
=> Add fake clock

package.json, src/client/nuclearnet/web_socket_proxy_nuclearnet_client.ts, src/server/nuclearnet/direct_nuclearnet_client.ts, src/server/nuclearnet/fake_nuclearnet_client.ts, src/server/nuclearnet/fake_nuclearnet_server.ts, src/server/nuclearnet/tests/fake_nuclearnet_client.tests.ts, src/shared/nuclearnet/nuclearnet_client.ts, yarn.lock
Supports new `onPacket` method, upgrades fakes to match.
In order to match the real behaviour, the fakes now need to use real hashes. Previously we were abstracting that away.
=> Upgrade NUClearNet.js to 1.4.2

src/server/dev.ts
Reconnecting clients were sometimes getting an invalid namespace error from socket.io if you restarted the server.
This was because `sioNetwork.of('/nuclearnet')` was not being called straight away to initialize the namespace. The connection listener also needs to be attached before `server.listen` is called.
This solves both these problems by moving it out of the async `init` function and instead straight after creating the socket.
=> Fix reconnection bug

src/client/canvas/renderer.ts
This makes the renderer have a single context save and restore operation in the renderObjects method.
=> Remove unnecessary context save/restore operations

src/simulators/overview_simulator.ts
Fixes the last seen icons in the dashboard.
=> Add timestamp to overview simulator

src/client/time/browser_clock.ts, src/server/time/node_clock.ts, src/server/time/tests/fake_clock.tests.ts, src/shared/time/clock.ts, src/shared/time/fake_clock.ts
This lets us use `process.nextTick` on the node side, and a faster equivalent to `setTimeout(fn, 0)` on the client side.
Also simplifies the interface, I don't think we'll ever use the `...args: any[]` part.
=> Replace setImmediate with nextTick

src/client/time/browser_clock.ts, src/server/time/node_clock.ts, src/server/time/tests/fake_clock.tests.ts, src/shared/time/clock.ts, src/shared/time/fake_clock.ts
Adds date functionality to the clock, supported by node + browser + fake.
Needed for recording!
=> Add date() to Clock interface

src/client/components/app/network.ts, src/client/components/dashboard/dashboard_robot/model.ts, src/client/components/dashboard/dashboard_robot/view_model.ts, src/client/components/dashboard/network.ts, src/client/components/dashboard/view.tsx, src/client/components/robot/model.ts, src/client/components/robot_selector/view.tsx
Prevents us trying to use `name` or some combination of `name`/`address`/`port` throughout the app, especially within react `key` properties.
Renames the current `id` property on `DashboardRobotModel` to `playerId`.
=> Add unique id to robot model

src/shared/time/fake_clock.ts, src/shared/time/tests/fake_clock.tests.ts
Noticed the fake clock tests were not living along-side the fake clock.
Added some type annotations while I was there 🙂
=> Move fake clock test to fake clock directory

src/server/nbs/nbs_frame_codecs.ts, src/server/nbs/tests/nbs_frame_codecs.tests.ts
Essentially, timestamps were not guaranteed to be written as an unsigned value because:
- `Long.fromNumber(-1).low === -1`
- `Long.fromNumber(-1).getLowBitsUnsigned() === 4294967295 === 0xFFFFFFFF`
So if the low 32 bits of the timestamp happened to be a negative value, the `writeUInt32LE` call in `encodeFrame` would throw with an out of bounds error.
By explicitly calling `getLowBitsUnsigned()` instead of accessing `low`, we're getting the correct unsigned value of the low bits.
p.s. this was already in the robocup recording branch, so they are all valid 🙂
=> Fix nbs timestamp encoding

src/client/canvas/object/group.ts, src/client/canvas/object/shape.ts, src/client/components/localisation/model.ts, src/client/math/matrix2.ts, src/client/math/matrix3.ts, src/client/math/transform.ts, src/client/math/vector2.ts, src/client/math/vector3.ts
There is no need for models to be annotated with `@action`.
Any consumer that uses these methods will already exist within a controller method which has an `@action` annotation.
i.e. these are redundant and also prevent the consumer from _needing_ to annotate themselves with `@action`.
=> Remove @action annotations on models

src/server/dev.ts, src/server/prod.ts, src/tests/networking_integration.tests.ts, src/virtual_robots/run.ts, src/virtual_robots/virtual_robot.ts, src/virtual_robots/virtual_robots.ts
Not all simulators should be created equal. This PR adds the ability to specify a frequency for each type of simulator.
I suspect this configuration will end up living inside each simulator eventually, but good enough for now.
- #135
- #136 ← You are here
- #137
=> Add per-simulator frequency configuration

src/server/nuclearnet/fake_nuclearnet_server.ts, src/server/nuclearnet/tests/__snapshots__/fake_nuclearnet_server.tests.ts.snap, src/server/nuclearnet/tests/fake_nuclearnet_server.tests.ts
When the hash code isn't 16 characters (because the MSBs are to small) the hash code was too short and broke everything.
This zero pads the resulting string to ensure it's always 16 characters.
=> Fix the hash function when the result isn't 16 characters

.gitignore, package.json, src/server/prod.ts, webpack.config.ts
The c++ bindings and prod had overlapping folders and were deleting eachother.
This moves the production build from `build` to `dist`
=> Fix production and node gyp having overlapping build folders

src/server/nbs/mmap_nbs_player/nbs_player.cpp
Compiling the NBS player on windows caused the following error:
`error C2440: 'reinterpret_cast': cannot convert from 'unsigned char' to 'uint8_t'`
=> Allows for NBS Player to compile on Windows

src/client/components/chart/line_chart/model.ts, src/client/components/chart/line_chart/view_model.ts, src/client/components/chart/model.ts, src/client/components/chart/network.ts
Currently, when there is a big difference between the timestamps on the datapoints and the clock, floating point errors make the resulting chart fail to display properly.
This PR corrects the times on each so they are all relative to the first point we see.
This makes all numbers involved smaller and corrects the error.
=> Relative chart times to prevent floating point error

src/client/components/chart/view.tsx
The chart view can take up a lot of CPU power when it's not used.
This stops it from using that while you're not even looking at it.
=> Change chart network lifetime to when in view

src/client/nuclearnet/tests/web_socket_proxy_nuclearnet_client.tests.ts, src/server/nbs/nbs_frame_chunker.ts, src/server/nbs/nbs_frame_codecs.ts, src/server/nbs/tests/nbs_frame_chunker.tests.ts, src/server/nbs/tests/nbs_frame_codecs.tests.ts, src/server/nbs/tests/nbs_frame_streams.tests.ts, src/server/nbs/tests/nbs_nuclear_playback.tests.ts, src/server/nuclearnet/tests/fake_nuclearnet_client.tests.ts, src/shared/nuclearnet/tests/nuclearnet_proxy_parser.tests.ts, src/virtual_robots/virtual_robot.ts
```
DeprecationWarning: Buffer() is deprecated due to security and usability issues.
Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
=> Replace deprecated buffer constructors

src/server/dev.ts, src/server/nuclearnet/lru_priority_queue.ts, src/server/nuclearnet/tests/lru_priority_queue.tests.ts, src/server/nuclearnet/web_socket_proxy_nuclearnet_server.ts, src/server/prod.ts
The general idea here is to keep client-side data as fresh as possible by biasing the packets we send towards the types we haven't sent recently.
i.e. we favour sending messages for event types that we have least recently sent.
The key used is `${event}:${packet.peer.name}:${packet.peer.address}:${packet.peer.port}`, which basically means we round-robin packets per-robot and per-event type, replacing anything old with newer packets as we go around.
Works pretty well!
=> Add priority queue to improve network performance

src/client/components/three/stories/three.stories.tsx, src/client/components/three/styles.css, src/client/components/three/three.tsx
Adds a new `Three` component designed to be used anywhere we require rendering of three.js scenes.
Its responsibilities:
- Take a `createStage` which produces a computed stage (a scene and camera pair).
- Provide the `width` and `height` of the canvas via an observable canvas object to `createStage`, which it can then use to (reactively) generate the scene from.
- Automatically re-render itself when the computed stage changes (by using a reaction).
- Resize itself to the container it is placed within.
- Eventually manage the horrible `Scene` memory leak problem (separate PR)
This PR also adds a storybook for the component with example usage. A separate PR will address the various memory leaks (such as disposing scenes/materials/geometries).
Storybook: …
=> Add Three component

src/server/dev.ts, src/server/prod.ts, src/tests/networking_integration.tests.ts, src/virtual_robots/run.ts, src/virtual_robots/simulator.ts, src/virtual_robots/simulators/chart_data_simulator.ts, src/virtual_robots/simulators/overview_simulator.ts, src/virtual_robots/simulators/script_data_simulator.ts, src/virtual_robots/simulators/sensor_data_simulator.ts, src/virtual_robots/simulators/vision_simulator.ts, src/virtual_robots/virtual_robot.ts, src/virtual_robots/virtual_robots.ts
The current setup of the simulators assumes a periodic simulator with a `simulate` method that is called at a regular interval to produce messages to send to NUsight.
This adds support for non-periodic simulators via the following:
- Rename current `Simulator` to `PeriodicSimulator`
- Add `Simulator` interface, with one method `start` which takes the network and returns a stop/cleanup function. In here we can listen for messages and send response messages using the network directly.
- Update `VirtualRobot` to have a list of simulators in addition to periodic simulators. When `startSimulators()` is called, we call `start()` on each simulator, in addition to setting an interval for the periodic simulators. The cleanup functions from `start()` are added to the stops list to be called on …
=> Add support for non-periodic simulators

src/client/components/app/view.tsx
Use Route's `component` prop for rendering, instead of `render`.
Fixes routing broken from #227.
=> Fix routing

conf/storybook/webpack.config.ts
`HotModuleReplacementPlugin` already included by `storybookConfig.plugins`, so we filter it out of `config.plugins`
=> Fix storybook console error

README.md, package.json
Installing the newest version of node (v12) results in compilation errors for NUClearNet.js. v10 is known to work (travis also uses v10 for testing).
=> Specifies version number for node.

src/client/components/switches_menu/menu_icon.svg, src/client/components/switches_menu/stories/switches_menu.stories.tsx, src/client/components/switches_menu/style.css, src/client/components/switches_menu/view.tsx, src/client/components/vision/camera/model.ts, src/client/components/vision/camera/view.tsx, src/client/components/vision/camera/view_model.ts, src/virtual_robots/simulators/vision_simulator.ts
This PR adds a dropdown menu on each camera image that allows for toggling the objects drawn (image, horizon, visual mesh, balls, goals, etc).
For the dropdown menu, I've added a new component `SwitchesMenu` which renders a dropdown menu where every option has a switch that can be toggled.
Storybook: https://nusight-pr-264.herokuapp.com/storybook/?path=/story/components-switches-menu--renders-empty
=> Add ability to toggle vision objects

src/client/components/robot_selector/stories/robot_selector.stories.tsx, src/client/components/robot_selector/style.css, src/client/components/robot_selector/view.tsx
This adds a connection indicator to the robot selector:
Green = connected
Gray outline = disconnected
Also adds stories for the robot selector component, since that was written before we had Storybook.
Storybook: https://nusight-pr-268.herokuapp.com/storybook/?path=/story/components-robot-selector--renders-empty
=> Add robot connection indicator

src/client/components/vision/camera/model.ts, src/client/components/vision/camera/shaders/mesh.vert, src/client/components/vision/camera/view_model.ts, src/client/components/vision/network.ts
Changes the vision view to display using rays instead of pixel coordinates so it is able to track as the camera rotates. Pulled from #267 which will become the update for the visual mesh view to do the same
=> Make the Vision view display the visual mesh using rays

conf/storybook/build_storybook.js, conf/storybook/webpack.config.ts
1. `CopyWebpackPlugin` was overwriting `index.html` producing a blank page
2. `HotModuleReplacementPlugin` isn't used anymore, so replacing that
=> Fix storybook

src/client/math/matrix2.ts, src/client/math/matrix3.ts, src/client/math/matrix4.ts, src/client/math/vector2.ts, src/client/math/vector3.ts, src/client/math/vector4.ts
Since we do it everywhere, this PR at least makes it relatively easy to convert between the types.
Added some `toString` helpers as well.
(p.s. if only we had typeclasses)
=> Add math three.js helpers

src/client/components/classifier/classified_image/view_model.ts, src/client/components/classifier/visualizer/view_model.ts, src/client/components/three/builders.ts
Adding some functionality to the three builders in preparation for the vision rewrite. e.g.
1. Separated uniforms from the shader, to prevent recompilation
2. Allowed `false`/`undefined`/`null` in `group` children arrays, and automatically filter them (handy for conditional objects in render trees)
3. Made a bunch of image params optional, with defaults (which match three.js)
4. Add support for some new things, like `InterleavedBuffer` and `frustumCulled`
=> Extend three builders

src/client/components/vision/grid_layout/grid_layout.tsx
`bestFitCols()` assumes there's at least one child, and crashes when there's none:
=> Fix crash in <GridLayout> when it has no children

docker, docker-compose.yml
Pairs with https://github.com/NUbots/NUbots/pull/341.
This adds a simple docker-compose file for running NUsight in a docker container to get it to talk to NUbots in a container on Windows.
Using `docker-compose` (instead of just `docker`) allows for creating the container on demand without a Dockerfile + `docker build`.
It also adds a shell script to make it easier to run the docker-compose commands. I considered adding the commands as scripts to `package.json`, but `yarn` reports two spurious errors on SIGINT exit.
---
To be used as follows (proper NUbook documentation coming soon), all commands run in WSL on Windows:
- Create the network: `docker network create nuclearnet`
- Make the docker script executable: `chmod +x ./docker`
- Install NUsight deps in the container `./docker yarn`
- …
=> Allow running in Docker on Windows and macOS

build_scripts/build.ts, conf/storybook/webpack.config.ts, src/server/dev-server.ts, src/server/dev.ts, webpack.config.ts
The `include` and `exclude` loader checks (see below) for CSS files in `node_modules/` currently don't work in development, as `__dirname` is `nusight/dist/` when the webpack config file is built, not `nusight/`.
https://github.com/NUbots/NUsight2/blob/ed96ed4d23aa909e93a5ae8e72f037e7826e01d0/webpack.config.ts#L59-L62
https://github.com/NUbots/NUsight2/blob/ed96ed4d23aa909e93a5ae8e72f037e7826e01d0/webpack.config.ts#L92-L98
=> Fix 3rd-party CSS files in development
